### PR TITLE
Catch incorrect timezones

### LINKED ISSUE #36: Absoulte path error can be incorrect in doSingleBackup
`doSingleBackup` checks for any `IllegalArgumentException` when calling `makeBackup`, and blames it on the path.
https://github.com/MaxMaeder/DriveBackupV2/blob/3484012271d20e2f59771b413b4aa20d2e2ead25/DriveBackup/src/main/java/ratismal/drivebackup/UploadThread.java#L268-L272

But an `IllegalArgumentException` can also come from formatting the time (line 82).
https://github.com/MaxMaeder/DriveBackupV2/blob/3484012271d20e2f59771b413b4aa20d2e2ead25/DriveBackup/src/main/java/ratismal/drivebackup/util/FileUtil.java#L74-L82

### PR DESCRIPTION
**Pull request by rhld16**
Should fix #36

### CODE REVIEW

File: DriveBackup/src/main/java/ratismal/drivebackup/config/Config.java [hunk 1]
```diff
@@ -225,6 +226,21 @@ private String getStringWithFallback(String path, String fallbackPath) {
...
+     * Returns the ZoneOffset in config, or if invalid use default
+     * 
+     * @param zoneId         the zone ID
+     * @return the value
+     */
+    private ZoneOffset getTimeWithFallback(String zoneId) {
+        try {
+            return ZoneOffset.of(zoneId);
+        } catch (DateTimeException exception) {
+            System.out.println("[DriveBackupV2] Timezone not valid, defaulting to 00:00");
```
Comment (MaxMaeder) [inline DriveBackup/src/main/java/ratismal/drivebackup/config/Config.java:239]: Can we instead use MessageUtil.sendConsoleMessage("message"); here?

Comment (MaxMaeder) [reply DriveBackup/src/main/java/ratismal/drivebackup/config/Config.java:239]: It will automatically prefix it with `[DriveBackupV2]`, so you can remove that from the message as well.

**Comment by rhld16** [comment]
Yes makes more sense - I did try using it but I didn't move the prefixColor above the schedules

**Comment by arielbeje** [comment]
This won't fix #36. 

This touches on parsing the global timezone, which is separate from parsing the format strings for `backup-list` (the issue in #36).

**Comment by MaxMaeder** [comment]
Ok, can you add functionality to catch the time zones in `backup list`?

**Comment by rhld16** [comment]
Oh oops - misread the issue. Will fix this as well then.

**Comment by rhld16** [comment]
That should work

**Comment by MaxMaeder** [comment]
Thanks!
